# Generated by Django 5.1.1 on 2024-12-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='post_date',
        ),
    ]
