# Generated by Django 5.1.1 on 2024-10-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='teks',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tanggal',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='nilai',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='judul',
            new_name='title',
        ),
    ]
