# Generated by Django 5.1.1 on 2024-10-26 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_game_alter_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='review_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
