# Generated by Django 5.1.2 on 2024-10-23 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('ratings', models.FloatField()),
                ('harga', models.CharField(max_length=255)),
            ],
        ),
    ]
