# Generated by Django 5.1.2 on 2024-10-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_comment'),
        ('search', '0004_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='search.game'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
