# Generated by Django 5.1.2 on 2024-10-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
