# Generated by Django 5.1.2 on 2024-10-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('ratings', models.FloatField()),
                ('harga', models.IntegerField()),
                ('toko1', models.CharField(max_length=255)),
                ('alamat1', models.CharField(max_length=255)),
                ('toko2', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat2', models.CharField(blank=True, max_length=255, null=True)),
                ('toko3', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
