# Generated by Django 5.1.2 on 2024-10-26 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('ratings', models.FloatField()),
                ('harga', models.IntegerField()),
                ('toko1', models.CharField(max_length=255)),
                ('alamat1', models.CharField(max_length=255)),
                ('toko2', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat2', models.CharField(blank=True, max_length=255, null=True)),
                ('toko3', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
