# Generated by Django 5.1.2 on 2024-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
    ]
