# Generated by Django 5.1.2 on 2024-10-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
